export default {
    SUBMIT_INFO: '[INFORMATION] SUBMIT_INFO',
    SUBMIT_INFO_RESULT: '[INFORMATION] SUBMIT_INFO_RESULT',
    SUBMIT_INFO_ERROR: '[INFORMATION] SUBMIT_INFO_ERROR',
    CLEAR_CACHE: '[INFORMATION] CLEAR_CACHE',
    GET_PRESENT: '[INFORMATION] GET_PRESENT',
    GET_PRESENT_RESULT: '[INFORMATION] GET_PRESENT_RESULT'
};
